<a href="https://colab.research.google.com/github/manojgupta3051994/dsmp-pre-work/blob/master/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
list1 = [1,2,3,4]
arr1 = np.array(list1)
print (arr1)
print (type(arr1))

In [5]:
arr_prod = arr1 + 2
print (arr_prod)

[3 4 5 6]


In [14]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(list2)
print (arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arr3 = np.array(list2,dtype=float)
arr3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
arr3.astype('bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [22]:
arr4 = np.array([1,0,10],dtype=bool)
arr4

array([ True, False,  True])

In [26]:
arr5  = np.array([1,'Manoj'],dtype=object)
arr5

array([1, 'Manoj'], dtype=object)

In [27]:
arr5.tolist()

[1, 'Manoj']

In [32]:
arr6 = np.arange(1,11)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr2.ndim

2

In [39]:
arr2.shape

(3, 3)

In [42]:
arr2.dtype

dtype('int64')

In [43]:
arr2.size

9

In [51]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2[1,0]

4

In [73]:
ar = arr2 > 5
ar

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [70]:
arr2[ar]

array([6, 7, 8, 9])

In [75]:
arr2[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [81]:
arr2.astype('int')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
arr2.max()

9

In [83]:
arr2.min()

1

In [84]:
arr2.mean()

5.0

In [86]:
np.amin(arr2,axis=1)

array([1, 4, 7])

In [88]:
np.amax(arr2,axis=1)

array([3, 6, 9])

In [89]:
np.cumsum(arr2)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [117]:
arr7 = arr2[1:,1:]
arr7

array([[5, 6],
       [8, 0]])

In [0]:
arr7[1:,1:]=9

In [119]:
arr7

array([[5, 6],
       [8, 9]])

In [120]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
arr7 = arr2[1:,1:].copy()

In [122]:
arr7

array([[5, 6],
       [8, 9]])

In [0]:
arr7[1:,1:]=0

In [126]:
arr7

array([[0, 6],
       [8, 0]])

In [127]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
arr8 = np.append(arr2,arr7,axis=1)

In [132]:
arr8

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 6, 8, 0])

In [135]:
arr8.shape

(13,)

In [0]:
arr9 = np.delete(arr8,12,axis=0)

In [146]:
arr9.reshape(6,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0],
       [6, 8]])

In [149]:
arr9.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 6, 8])

In [151]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [152]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [155]:
np.repeat(arr9,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 0, 0, 6, 6,
       8, 8])

In [156]:
np.random.rand(2,2)

array([[0.36634603, 0.80002071],
       [0.06557537, 0.72852377]])

In [165]:
np.random.randint(1,10,size=[2,2])

array([[2, 4],
       [3, 1]])

In [161]:
np.random.randn(1,10)

array([[-0.07669259,  0.76046928,  0.28301787, -0.02203075, -1.03367708,
        -0.61339132, -1.99854906, -1.33444681,  0.28793347,  0.04132193]])

In [0]:
arr10 = np.arange(0,10)

In [0]:
get_index= np.where(arr10>5)

In [175]:
arr10.take(get_index)

array([[6, 7, 8, 9]])

In [176]:
np.where(arr10>5,'Y','N')

array(['N', 'N', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'Y'], dtype='<U1')

In [177]:
np.max(arr10)

9

In [178]:
np.min(arr10)

0

In [179]:
arr10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
arr9

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 6, 8])

In [185]:
np.delete(arr9,11,axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 6])

In [186]:
arr9

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 6, 8])

In [0]:
a= np.zeros([5,5])
b = np.ones([5,5])

In [193]:
np.concatenate([a,b],axis = 0)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [196]:
np.vstack([a,b])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [198]:
np.concatenate([a,b],axis=1)
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])

In [207]:
arr11 = np.random.randint(1,10,size=[8,4])
arr11

array([[6, 3, 5, 2],
       [7, 9, 1, 4],
       [4, 9, 8, 6],
       [7, 3, 8, 1],
       [9, 1, 1, 7],
       [8, 4, 5, 9],
       [1, 8, 2, 7],
       [7, 9, 5, 9]])

In [209]:
np.sort(arr11,axis=1)

array([[2, 3, 5, 6],
       [1, 4, 7, 9],
       [4, 6, 8, 9],
       [1, 3, 7, 8],
       [1, 1, 7, 9],
       [4, 5, 8, 9],
       [1, 2, 7, 8],
       [5, 7, 9, 9]])

In [0]:
arr12 = np.array([1,10,5,2,8,9])

In [0]:
sort_index = np.argsort(arr12)

In [212]:
sort_index

array([0, 3, 2, 4, 5, 1])

In [213]:
arr12[sort_index]

array([ 1,  2,  5,  8,  9, 10])

In [216]:
arr11[0,:].argsort()

array([3, 1, 2, 0])

In [215]:
arr11

array([[6, 3, 5, 2],
       [7, 9, 1, 4],
       [4, 9, 8, 6],
       [7, 3, 8, 1],
       [9, 1, 1, 7],
       [8, 4, 5, 9],
       [1, 8, 2, 7],
       [7, 9, 5, 9]])

In [217]:
arr11[sort_index[::-1]]

array([[7, 9, 1, 4],
       [8, 4, 5, 9],
       [9, 1, 1, 7],
       [4, 9, 8, 6],
       [7, 3, 8, 1],
       [6, 3, 5, 2]])